// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpzHc9OAy3eXhmBnynjq81RmFvSo8ZuP8',
    appId: '1:261676923216:web:27ed6ca41a51b36458d455',
    messagingSenderId: '261676923216',
    projectId: 'bank-app-9b79c',
    authDomain: 'bank-app-9b79c.firebaseapp.com',
    storageBucket: 'bank-app-9b79c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTMEPONFTQFT1KV2ZtQjv-MMQNrtp78_g',
    appId: '1:261676923216:android:03d1629f90e6337258d455',
    messagingSenderId: '261676923216',
    projectId: 'bank-app-9b79c',
    storageBucket: 'bank-app-9b79c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4DKe53Ujim-7rnCaHVhZoGiZqH1Rbag',
    appId: '1:261676923216:ios:69b493d998266f5a58d455',
    messagingSenderId: '261676923216',
    projectId: 'bank-app-9b79c',
    storageBucket: 'bank-app-9b79c.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4DKe53Ujim-7rnCaHVhZoGiZqH1Rbag',
    appId: '1:261676923216:ios:69b493d998266f5a58d455',
    messagingSenderId: '261676923216',
    projectId: 'bank-app-9b79c',
    storageBucket: 'bank-app-9b79c.firebasestorage.app',
    iosBundleId: 'com.example.bankApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpzHc9OAy3eXhmBnynjq81RmFvSo8ZuP8',
    appId: '1:261676923216:web:b23a959cbc9f150858d455',
    messagingSenderId: '261676923216',
    projectId: 'bank-app-9b79c',
    authDomain: 'bank-app-9b79c.firebaseapp.com',
    storageBucket: 'bank-app-9b79c.firebasestorage.app',
  );
}
